# Generated by Django 6.0.3 on 2026-05-08 12:33

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название кейса')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/', validators=[common.validators.validate_image_size, common.validators.validate_image_extension])),
                ('results', models.TextField(blank=True, verbose_name='Результаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
