# Generated by Django 6.0.3 on 2026-03-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_type', models.CharField(choices=[('voice', 'Голосовой бот'), ('chat_voice', 'Чат/голосовой бот для записи'), ('consultant', 'Чат/голосовой бот консультант'), ('nps', 'Чат/голосовой бот для NPS-опросов'), ('notify', 'Голосовой/чат/смс бот для напоминаний')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('price_from', models.IntegerField(verbose_name='Цена от (руб)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='bots/')),
                ('cost_reduction', models.CharField(blank=True, max_length=50, verbose_name='Сокращение затрат')),
                ('conversion_increase', models.CharField(blank=True, max_length=50, verbose_name='Рост конверсии')),
                ('time_saving', models.CharField(blank=True, max_length=50, verbose_name='Экономия времени')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
    ]
