# Generated by Django 6.0.3 on 2026-05-08 12:33

import common.models_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_type', models.CharField(choices=[('voice', 'Голосовой бот'), ('voice_chat', 'Голосовой/чат бот'), ('recording', 'Бот для записи'), ('consultant', 'Бот-консультант'), ('nps', 'Бот для NPS-опросов'), ('notify', 'Бот для напоминаний и рассылок')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('price_from', models.IntegerField(verbose_name='Цена от (руб)')),
                ('icon', models.CharField(default='fa-robot', max_length=50, verbose_name='Иконка')),
                ('cost_reduction', models.CharField(blank=True, max_length=50, verbose_name='Сокращение затрат')),
                ('conversion_increase', models.CharField(blank=True, max_length=50, verbose_name='Рост конверсии')),
                ('time_saving', models.CharField(blank=True, max_length=50, verbose_name='Экономия времени')),
                ('advantages', models.TextField(blank=True, verbose_name='Преимущества')),
                ('results', models.TextField(blank=True, verbose_name='Результаты')),
                ('tags', models.TextField(blank=True, verbose_name='Теги')),
                ('integrations', models.TextField(blank=True, verbose_name='Интеграции')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
            bases=(models.Model, common.models_mixins.TextListMixin),
        ),
    ]
