# Generated by Django 6.0.3 on 2026-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='advantages',
            field=models.TextField(blank=True, verbose_name='Преимущества'),
        ),
        migrations.AddField(
            model_name='bot',
            name='integrations',
            field=models.TextField(blank=True, verbose_name='Интеграции'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('voice', 'Голосовой бот'), ('voice_chat', 'Голосовой/чат бот'), ('recording', 'Бот для записи'), ('consultant', 'Бот-консультант'), ('nps', 'Бот для NPS-опросов'), ('notify', 'Бот для напоминаний и рассылок')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='icon',
            field=models.CharField(default='fa-robot', max_length=50, verbose_name='Иконка'),
        ),
    ]
