# Generated by Django 6.1 on 2026-08-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('callback', 'Обратный звонок'), ('contact', 'Контакты'), ('consultation', 'Консультация по боту'), ('partner', 'Партнёрство'), ('ai_lab', 'AI Lab')], max_length=20, verbose_name='Тип заявки')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('bot_name', models.CharField(blank=True, max_length=200, verbose_name='Бот')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('status', models.CharField(choices=[('not_processed', 'Не обработано'), ('processed', 'Обработано'), ('replied', 'Отвечено'), ('expired', 'Просрочено')], default='not_processed', max_length=20, verbose_name='Статус заявки')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Телефон подтверждён через AI Lab')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
