# Generated by Django 6.1 on 2026-08-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('badge', 'Партнёрский бейдж (TWIN, Сколково)'), ('client', 'Логотип клиента')], default='client', max_length=20, verbose_name='Тип'),
        ),
    ]
