# Generated by Django 6.1 on 2026-08-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=45, verbose_name='IP')),
                ('path', models.CharField(max_length=500, verbose_name='URL')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='Referer')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-created_at'],
            },
        ),
    ]
